name: Update builds

on: workflow_dispatch

jobs:
  update-builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name kraxarn
          git config user.email kraxarn@users.noreply.github.com

      - name: Download Linux build
        run: |
          source update.sh
          download_artifact "7734249" "linux.zip"
          unzip "linux.zip"
          find . -name "spotify-qt-*.AppImage" -exec mv {} ./spotify-qt-linux-nightly.AppImage \;
          git add "spotify-qt-linux-nightly.AppImage"

      - name: Upload Builds
        run: |
          git commit -m "$(source_hash)"
          git push
