name: Update builds

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Builds
        env:
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        run: |
          python update.py